MvcAuth/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcAuth.Models;

namespace MvcAuth.Controllers
{
    public class ProfessorController : Controller
    {
        // GET: Professor
        SmartModel1 Db = new SmartModel1();
        public ActionResult FileUpload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FileUpload(HttpPostedFileBase files)
        {

            String FileExt = Path.GetExtension(files.FileName).ToUpper();

            if (FileExt == ".PDF")
            {
                Stream str = files.InputStream;
                BinaryReader Br = new BinaryReader(str);
                Byte[] FileDet = Br.ReadBytes((Int32)str.Length);

                Prof_Lecture_TBL Fd = new Prof_Lecture_TBL();
               
                Fd.Prof_Lecture_Name = files.FileName;
                Fd.Prof_Lecture = FileDet;
                Fd.Prof_ID = 1;
                Db.Prof_Lecture_TBL.Add(Fd);
                Db.SaveChanges();
                return RedirectToAction("FileUpload");
            }
            else
            {

                ViewBag.FileStatus = "Invalid file format.";
                return View();

            }
        }
        [HttpGet]
        public PartialViewResult FileDetails()
        {
            List<Prof_Lecture_TBL> DetList = Db.Prof_Lecture_TBL.ToList();

            return PartialView("FileDetails", DetList);
        }
        [HttpGet]
        public FileResult DownLoadFile(int id)
        {


            List<Prof_Lecture_TBL> ObjFiles = Db.Prof_Lecture_TBL.ToList();

            var FileById = (from FC in ObjFiles
                            where FC.Prof_Lecture_ID.Equals(id)
                            select new { FC.Prof_Lecture_Name, FC.Prof_Lecture }).ToList().FirstOrDefault();

            return File(FileById.Prof_Lecture, "application/pdf", FileById.Prof_Lecture_Name);

        }
    }
}

MvcAuth/Views/Professor/FileDetails.cshtml
@model IEnumerable<MvcAuth.Models.Prof_Lecture_TBL>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProfessorTbl.Prof_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prof_Lecture_Name)
        </th>
        <th>
           
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
      
        <td>
            @Html.DisplayFor(modelItem => item.ProfessorTbl.Prof_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prof_Lecture_Name)
        </td>
        <td>
            @Html.ActionLink("Downlaod", "DownLoadFile", new { id = item.Prof_Lecture_ID })
        </td>
    </tr>
}

</table>

MvcAuth/Views/Professor/FileUpload.cshtml
@model MvcAuth.Models.EmpModel



@using (Html.BeginForm("FileUpload", "Professor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.files, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.files, "", new { @type = "file", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.files, "", new { @class = "text-danger" })
        </div>
       
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.FileStatus
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-8">
                @Html.Action("FileDetails", "Professor")
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>  